apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: examples-calls-android
  description: Public sample repository for Sendbird calls sample android
  annotations:
    github.com/project-slug: sendbird/examples-calls-android
spec:
  type: library
  lifecycle: production
  owner: dep-client-platform
  system: sendbird-calls

